# Generated by Django 6.0.7 on 2026-07-25 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("MANAGER", "Manager"),
                            ("LEAD", "Team Lead"),
                            ("MEMBER", "Team Member"),
                        ],
                        default="MEMBER",
                        max_length=10,
                    ),
                ),
                ("designation", models.CharField(blank=True, max_length=100)),
                (
                    "sn_user_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ServiceNow user ID"
                    ),
                ),
                ("assignment_group", models.CharField(blank=True, max_length=100)),
                (
                    "skills",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated, e.g. SAP, Java, Oracle",
                        max_length=255,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "annual_leave_balance",
                    models.DecimalField(decimal_places=1, default=24, max_digits=5),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
