# Generated by Django 6.0.7 on 2026-07-25 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50, unique=True)),
                ("short_description", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("priority", models.CharField(default="P3", max_length=2)),
                ("state", models.CharField(default="New", max_length=50)),
                ("opened_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_to", models.CharField(blank=True, max_length=100)),
                ("assignment_group", models.CharField(blank=True, max_length=100)),
                ("sla_met", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("client_name", models.CharField(blank=True, max_length=100)),
                ("file", models.FileField(upload_to="templates/")),
                (
                    "is_client_approved",
                    models.BooleanField(
                        default=True, verbose_name="Client-approved template"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DSR", "Daily Status Report"),
                            ("WSR", "Weekly Status Report"),
                            ("MSR", "Monthly Status Report"),
                        ],
                        max_length=3,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("file", models.FileField(upload_to="reports/")),
                ("highlights", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank = built-in default template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
