# Generated by Django 6.0.7 on 2026-07-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive shifts stay on old rosters but can't be newly assigned.",
            ),
        ),
    ]
