# Generated by Django 6.0.7 on 2026-07-26 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Control-M job name", max_length=120, unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("INFRA", "Infrastructure"),
                            ("PIPELINE", "Data Pipeline"),
                            ("OTHER", "Other"),
                        ],
                        default="PIPELINE",
                        max_length=10,
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=6,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Daily 02:00" or "Mon-Fri 23:30"',
                        max_length=100,
                    ),
                ),
                ("cluster", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("RUNNING", "Running"),
                            ("SKIPPED", "Skipped"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="e.g. failure reason / INC number",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="operations.batchjob",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-run_date"],
                "unique_together": {("job", "run_date")},
            },
        ),
    ]
