# Generated by Django 6.0.7 on 2026-07-26 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cr_number",
                    models.CharField(
                        help_text="e.g. CHG0034567",
                        max_length=50,
                        unique=True,
                        verbose_name="CR number",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("engineering_contact", models.CharField(blank=True, max_length=100)),
                ("affected_system", models.CharField(blank=True, max_length=100)),
                (
                    "target_date",
                    models.DateField(
                        blank=True, help_text="Planned implementation date", null=True
                    ),
                ),
                (
                    "runbook",
                    models.FileField(blank=True, null=True, upload_to="runbooks/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("WT_SCHEDULED", "Walkthrough scheduled"),
                            ("WT_HELD", "Walkthrough held"),
                            ("REVIEW_1", "First review sent"),
                            ("REVIEW_2", "Second review sent"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="RECEIVED",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CREATED", "Change registered"),
                            ("RUNBOOK_RECEIVED", "Runbook handed over"),
                            ("WT_SCHEDULED", "Walkthrough scheduled"),
                            ("WT_HELD", "Walkthrough held"),
                            ("REVIEW_1", "First review sent to engineering"),
                            ("REVIEW_2", "Second review sent to engineering"),
                            ("APPROVED", "Change approved"),
                            ("REJECTED", "Change rejected"),
                            ("COMMENT", "Comment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True, help_text="Walkthrough date/time", null=True
                    ),
                ),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="operations.changerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["at"],
            },
        ),
    ]
