# Generated by Django 6.0.7 on 2026-07-26 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_changerequest_changeevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="changeevent",
            name="recorded_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When it was entered in the portal",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="changeevent",
            name="at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the milestone actually happened",
            ),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Planned implementation / deployment date",
                null=True,
                verbose_name="Implementation date",
            ),
        ),
    ]
